version: '3'

services:

    chatserver:
        build:
            context: ./services/chatServer
            dockerfile: Dockerfile-dev
        security_opt:
            - seccomp:unconfined
        volumes:
            - './services/chatServer:/usr/src/app'
        expose:
            - '5000'
        environment:
            - FLASK_APP=project/app.py
            - FLASK_ENV=development
            - APP_SETTINGS=project.config.DevelopmentConfig
            - DATABASE_URL=postgres://postgres:postgres@chat-db:5432/chat_dev
            - DATABASE_TEST_URL=postgres://postgres:postgres@chat-db:5432/chat_test
        depends_on:
            - chat-db

    chat-db:
        build:
            context: ./services/chatServer/project/db
            dockerfile: Dockerfile
        security_opt:
            - seccomp:unconfined
        ports:
            - 5435:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres

    client:
        build:
          context: ./services/client
          dockerfile: Dockerfile-dev
        volumes:
          - './services/client:/usr/src/app'
          - '/usr/src/app/node_modules'
        ports:
          - 3007:3000
        environment:
          - NODE_ENV=development
        depends_on:
          - chatserver

    nginx:
        build:
            context: ./services/nginx
            dockerfile: Dockerfile-prod
        restart: always
        ports:
            - 80:80
        depends_on:
            - chatserver
            - client
